### PR TITLE
Added Thunderforest maps

### PR DESCRIPTION
**Pull request by sikmir**
* [Thunderforest Maps](http://thunderforest.com/maps/)
* [Terms and Conditions](http://thunderforest.com/terms/) (API keys are required for all services)

### CODE REVIEW

**Comment by tumic0** [comment]
I'm really in doubts whether we shall enable maps that don't work "out-of-the-box". They may look "broken" for many users...

**Comment by sikmir** [comment]
We can remove `?apikey=insert-your-apikey-here` part. So result will be more "workable":
screenshot1
Anyway these maps are very popular.

**Comment by tumic0** [comment]
Yes, but then adding the API key will not be that easy as people would have to search for the parameter name. My idea is to let the parameter there, but name the file not *.xml but *.tpl (or *.template). This way people would see that it is a template (and it won't be possible to load it into GPXSee unless they change the extension)

**Comment by sikmir** [comment]
This sounds reasonable. Let's do it in such a way.

**Comment by sikmir** [comment]
GH is confused about `*.tpl` files:
screenshot1
Linguist definition for [Smarty](https://www.smarty.net/):
https://github.com/github/linguist/blob/cc4da9861689e2a2ec9a7602c2b0b0163619a66a/lib/linguist/languages.yml#L4419-L4427
You can fix it by adding:
```sh
$ echo "*.tpl linguist-language=xml" > .gitattributes
```

**Pull request merged**
