### PR TITLE
Add BGMountains map from http://www.kade.si

### PR DESCRIPTION
**Pull request by trundev**

### CODE REVIEW

**Comment by tumic0** [comment]
Please add a copyright entry to the map definition (something like "CC-BY-NC-SA 2.5 bg", see the other maps for examples)

**Comment by trundev** [comment]
I have nothing to do with this service, but the web-page includes an "attributions" button, that shows "CART Lab, BGM team, Tiles © CC BY-SA 4.0". Do you think this should be added?

**Comment by tumic0** [comment]
Yes, something like that.

**Comment by trundev** [comment]
Ok, please check the last commit.

**Comment by tumic0** [comment]
The copyright character does not look like a proper UTF8 character...

**Comment by trundev** [comment]
Sorry! Must be fixed now.

**Pull request merged**
